### ISSUE TITLE
Idea for hyperapp router

### ISSUE THREAD

**Issue by jcubic** [hyperapp/hyperapp#295] opened 2017-07-13 08:40 UTC
I want to add simple router to hyperapp, I thought that I use something like react router.

I can use url hash as state property, but I need to access action from outside of app, is there something like

init actions:

```javascript
actions: {
  init: function(state, actions) {
    window.addEventListener('hashchange', function() {
      actions.url(localhost.hash.replace(/^#/, ''));
    });
  },
  url: function(state, actions, url) {
    return {url};
  }
}
```

Second I want to create Route widget but I need to have something like children
(Something like angularjs transclude or react props.children)

```javascript
const Route = ({path, url}) => {
    if (match(path, url) {
       return ( children );
    }
}
```

so I can use:
```javascript
app({
  state: {url: localhost.hash.replace(/^#/, ''))},
  view: (state, actions) => (
     <div>
       <Route path={"/user"} url={state.url}>
         <p>user</p>
       </Route>
       <Route path={"/category"} url={state.url}>
         <p>category</p>
       </Route>
     </div>
  ),
  actions: {
    init: function(state, actions) {
      window.addEventListener('hashchange', function() {
        actions.url(localhost.hash.replace(/^#/, ''));
      });
    },
    url: function(state, actions, url) {
      return {url};
    }
  }
});
```

are those two things possible with hyperapp?

**Comment by jcubic** [comment] 2017-07-13 08:59
Just notice you TodoMVC app is the router build in? Is it possible to use it with hash? From where this Route mixing coming from? In the app there is:
```javascript
import { h, app, Router } from "hyperapp"
```
but I can find it in repo.

**Comment by zaceno** [comment] 2017-07-13 09:08
I think this idea is promising and, to me, a more useful type of router.

Mostly this should be possible!

For the route as state, you could make a state property that tracks the URL by adding an event listener on "hashchange" (in the init event of the app/mixin) 

For the route component: you do get the children passed to it. The signature is `(props, children) -> vnode `  The only problem is that your component cant return an array of children, it needs to return a single vnode (which may in turn contain children) But I'm sure some nice solution can be designed around that limitation.

**Comment by zaceno** [comment] 2017-07-13 09:09
The router was recently moved to a separate repo hyperapp/router 

The todo Mvc example just hasn't been updated yet

**Comment by zaceno** [comment] 2017-07-13 09:10
The current router doesn't yet support hash routes (I don't think) but it's been discussed!

**Comment by jcubic** [comment] 2017-07-13 09:16
Great, thanks. Will take a look into hyperapp/router and into mixins.

**Comment by jcubic** [comment] 2017-07-13 10:55
I have basic app working https://codepen.io/jcubic/pen/mwvMBV?editors=0010

but now I have problem I need to access data from Route widget inside children (to display selected user), to do this I need to update state from widgets but that's I believe is not possible because widgets are stateless.

Any idea how to resolve this? Maybe emit event from widget that will be accessed from Mixin?

**Comment by zaceno** [comment] 2017-07-13 11:41
Took a look at your example, but not sure I understand what it is you're trying to achieve. Your example seems to work fine, as you say.

If you need to modify state, that needs to be done via actions. In your example, children of the `Route` have the actions and state in their scope, so they can just use them.

If you're planning to separate out the children of Route (like one component for each state) (defined outside the main `app.view`)  Then yes, you'd need to forward the state / actions to them. Simply passing the state/actions along as props is a simple (not the most elegant perhaps) way:

```jsx
app({
...
view: (state, actions) => 
  <Route path={"/user/{{name}}"} route={state.route}>
       <UserPage state={state} actions={actions} /> 
  </Route>
})
```

**Comment by zaceno** [comment] 2017-07-13 11:43
fwiw I've been working on and off on a solution for mixins with components that get pre-bound to the `state` and `actions` ( I call such components "widgets") so that you can use them without passing state/actions to them explicitly

**Comment by jcubic** [comment] 2017-07-13 11:51
That would be awesome, just like components in react+redux, I was looking for something like this.

**Comment by zaceno** [comment] 2017-07-13 12:01
Cool! Here's how far I got: https://codepen.io/zaceno/pen/YQjwNa

As you can see it basically works, without changing hyperapp's core, But on the other hand, it's kind of a lot of extra code, and you may want a simpler solution. But by all means use that as an inspiration. :)

**Comment by jcubic** [comment] 2017-07-13 19:15
Your code is interesting but it's lot of code it would be nice if widgets with state and actions would be supported by hypperapp itself. Maybe something like in React when you can have simple functions and classes, I'm thinking about forking the project.

As you suggested I've added actions to Route widget and I'm calling action to update route data from inside Route widget but data is not updating. It's always one step behind. To show user data for foo I need to click foo and then bar. I think that chaning state when widgets are created are ignored (maybe to prevent infinite loop) the same code https://codepen.io/jcubic/pen/mwvMBV?editors=0010

Will try to register the route in route mixin when Route is first called, maybe that will fix the issue.

**Comment by zaceno** [comment] 2017-07-13 19:37
@jcubic  You're right, it is a lot of code. Also, it does more than just widgets (there's the whole "scoped mixin" concept baked in there as well). Anyway it's not done, I'm just kind of playing with patterns to figure out what could/should go into core and what can be left in userland (if the pattern is useful at all -- I kind of took a break from the project to write some actual apps and battle test the patterns before proceeding)

I had a look at your code and I'm pretty sure what the problem is. You're right, its sort of to prevent an infinite loop. Because you call an action directly in the Route component (while it's being rendered, in effect) -- and that would normally cause another render loop, another action, render, action.... 

But as of recently we "debounce" renders with requestAnimationFrame, so actions called during the ongoing render will not cause a new render. That's why you're seeing the "one-step-behind" effect in your route data.

**Comment by SkaterDad** [comment] 2017-07-13 19:54
@jcubic When I run your codepen, there's a runtime error because "data" is not defined in the Route function.
```js
const Route = ({route, path, actions}, children) => {
  if (route.routes.indexOf(path) == -1) {
    actions.router.register(path);
  }
  console.log(route);
  if (path == route.selected) {
    return (
      <div>
        <p>{JSON.stringify(data)}</p> // <--- Error here
        {children}
      </div>
    );
  }
};
```

I'm not sure I understand why you think component classes are needed in this case.  Could you explain what problem that would solve for you?

Hyperapp has a fundamentally different approach than React, since it was inspired by Elm and the idea of having a single state tree, so it may take different patterns to achieve the same end result.

**Comment by jcubic** [comment] 2017-07-13 19:57
Registering route with mixin work but not all the time, maybe there is some race condition bug in hyperapp. I'm chaning hash at the beginning of the script (normal hash don't work on codepen)

If you refresh the page few times sometimes you get Route "/user/{{name}}" and User foo and sometime you don't. Is it a bug? I'm calling action inside widget before it return jsx.

https://codepen.io/jcubic/pen/mwvMBV?editors=0010

**Comment by zaceno** [comment] 2017-07-13 20:12
> I'm calling action inside widget before it return jsx.

This will generally cause trouble, because calling the action inside there will cause a render while already in a render.

This solution: https://codepen.io/zaceno/pen/YQBBgE?editors=0010 (forked off your earlier version, only diff is line 45) seems to work well. *But* I don't really like the solution since it will effectively render the entire vdom twice for each update. (once for any other state updates, and then once again after we've "picked" the data, since we don't pick data until rendertime)

**Comment by SkaterDad** [comment] 2017-07-13 20:18
> Maybe the router mixin could register all the routes to match (including capture-params like {{name}} in your case) on the first render and then the router.set action could take care of both setting the route and picking the data.

Was thinking the same thing. :+1: 

Hyperapp will work best if the view is a simple `state -> view` function without side effects.

**Comment by jcubic** [comment] 2017-07-13 20:19
@SkaterDad it would simplify the app because you don't need to pass state in widgets that return other widgets, and I'm not referring to pure react but redux that have one state tree and each component can map global state object to props so you don't need to use real properties. and the same happen with dispatch that are like actions. That way you can have widgets like `<Todos/>` that don't have props but there are taken from redux mapping. In redux you do something like this:

```javascript
const map_state_to_props = (state) => {
    return {
        grid: state.grid
    };
};

const map_dispatch_to_props = (dispatch) => {
    return {
        change_grid: (index) => {
            dispatch({
                type: 'CHANGE_GRID',
                index: index
            });
        }
    }
};

export default connect(map_state_to_props, map_dispatch_to_props)(Navigation);
```

Hyperapp could do the same as redux but instead of mapping for state and actions to properties it can just use state object and actions in widgets object it would simplify the implementation and will work like redux is build in.

Maybe something like:
```
let Navigation = widget((state, action, options, children) => {
   return <nav>
      <p>{state.page}</p>
      <a onclick={actions.change("foo")}>foo</a>
   </nav>
}):
```
and the Object or function returned by widget will be able to use the same as normal widget function that will stay the same. If I need to access more actions and state objects I ended up with widgets that look like this:
```
<Navigation state={state} actions={actions}/>
```
it make no sens to repeat that for every widget if that can be passed to widgets by the framework.

**Comment by jbucaran** [comment] 2017-07-16 14:43
@jcubic @zaceno @SkaterDad Do you think we can move this discussion to https://github.com/hyperapp/router and close here? 👋

**Comment by zaceno** [comment] 2017-07-16 19:15
@jbucaran: I (speaking only for myself, of course) think we can close this here, but don't think we need to move anything to the router-repo, because as of yet we don't have anything concrete.

But in saying we can close the issue, I don't mean the discussion should end -- quite the opposite!
(Is it possible to migrate an entire issue with all the discussions et c from one repo to another?)

The basic idea of mapping routes to state rather than views is sound, but so different from the official router that it's probably best implemented as an unofficial alternative.

However, I think I've found a significant problem with implementing a react-style router for hyperapp (with `<Route match="...` style components). And that is: JSX translates the component tree into a tree of `h(...)` calls, and these calls will be executed depth-first (that's just how javascript works). So that means that for every route -- even all the ones that *don't* match, the child-trees will have to be built. So *all* the "pages" of an app must be built (even if we don't end up showing them) for every state update. That obviously doesn't scale  -- and will probably be riddled with runtime errors if you expect state vars to exist that don't in unmatched routes.

I honestly don't know how react-router get's around this problem. Probably they can get around the issue thanks to their component architecture somehow. I imagine a react component is kind of like a HyperApp-app in itself, managing it's own vdom.

The best I've been able to come up that is almost the same:

Instead of this:
```jsx
...
<Router match="/users/foo">
  <UserPage user="foo" />
</Router>
...
```

you have this:

```jsx
...
{emit('router:match?', '/users/foo') && <UserPage user="foo" />}
...
```

It works because by using the `&&` operator, javascript will skip evaluation of the the right hand operand if the left hand is falsy.

This also means we can't use the "nested matching" or whatever it's called (where you can match on the first part of the route, and then in the child match on a follwing part, and below that another part et c.... That's what lets the react-router do that cool "recursive routes" trick. But I don't see how that's possible in hyperapp (without tossing performance and scalability completely out the window)

**Comment by SkaterDad** [comment] 2017-07-17 01:54
I agree this could be closed.  Also not sure it's worth migrating any of this to the router repo.

What this discussion highlights to me is that JSX makes things awkward since you're forced to write your functions in a very specifc way.  I don't personally use it, so it's hard for me to relate.  I see the appeal, but it seems restrictive.

@jcubic 's example of `<Navigation state={state} actions={actions}/>` could just be `Navigation(state, actions)` in vanilla JS land.

Here is a plain JS example from my own router experimentation.  A `RouterView` function, used in a `Layout` function.  There's a predefined `routes` array like you'd see in other frameworks.  The same philosophy could be adapted for RR4-style routing, I think, if you expose the `match` function to the view.
```js
function RouterView(state, actions) {
  const route = routes.filter(r => r.path === state.router.match)[0] || {}
  if (route.view === undefined) return null
  return typeof route.view === "function" ? route.view(state, actions) : route.view
}

const Layout = (model, actions, children) => {
  return h('div', { id: 'layout' }, [
    h('header', {}, [
      h('h1', {}, 'Site Name'),
      h('nav', {}, [
        Link(actions.router, { to: '/', text: 'Home', attrs: {}}),
        Link(actions.router, { to: '/about', text: 'About', attrs: {}}),
        Link(actions.router, { to: '/about/1', text: 'About 1', attrs: {}}),
        Link(actions.router, { to: '/about/1?test=[2,3]', text: 'About Array', attrs: {}})
      ])
    ]),
    h('main', { class: 'page' }, RouterView(model, actions))
  ])
}
```

**Comment by zaceno** [comment] 2017-07-17 09:09
Interesting! Because it should be possible to expose the match function to all views, if you make it an event, and "call" it using emit. So you wouldn't have to pass it along as a prop (although you certainly could, the emit-pattern lends itself more nicely for wrapping it all up in a mixin)

**Comment by lukejacksonn** [comment] 2017-07-18 00:33
I :heart: where this is going! @SkaterDad I am going to take inspiration from that last example and have a play.. I feel a component based router like this are the way to go. One state and one view feels _right_ (so long as there is no redundant processing of `h` functions that @zaceno points out). 

In that [RR4 talk](https://www.youtube.com/watch?v=Vur2dAFZ4GE) they were really hinting that this was there _ah ha_ moments.

> The router is just a react component
> In the "react-router" the emphasis in no longer on the router but on react

`s/react/hyperapp`

**Comment by jbucaran** [comment] 2017-08-09 10:58
@SkaterDad @jcubic @zaceno @lukejacksonn 

To help me clarify things up a bit, is this what we are after:

```jsx
  <Route path={"/user/{{name}}"} route={state.route}>
       <UserPage state={state} actions={actions} /> 
  </Route>
```

🤔

**Comment by zaceno** [comment] 2017-08-09 14:41
@jbucaran yes, essentially. It would also be nice with support for nested routes, so a Route tag inside another would match on the remainder. I think that's how the latest react-router is able to do that neat "recursive routes" trick.

**Comment by zaceno** [comment] 2017-08-09 16:29
@jbucaran 
> Would you be able to put together a minimal, cut-to-the-chase & not-bog-down-on-details requirements spec for this new router API?

Hmm... I'll have to think more about it. I haven't worked on/with routers enough to know what features are essential.🤔 

The thing *I* see as important and different from the current router, is that we should consider the route -- including dynamic segments and perhaps even query parameters et c -- a *part of the state* and available on the state object. That way you can chose what to render at multiple levels in your view functions -- in more complex and useful ways that just simple: "if this route - show this view"

To me that's more relevant than implementing something like the `<Route>` component you described above. It is a prerequisite for it though. The `<Route>` component was more what the OP @jcubic was after.

>>  Route tag inside another would match on the remainder

> Can you reword this sentence please?

Not in as few words, I don't think. I'm basically talking about what's called "nested routes" in vue-router (https://router.vuejs.org/en/essentials/nested-routes.html) as well as react I think. Or consider this example of recursive routing in react: https://reacttraining.com/react-router/web/example/recursive-paths

**Comment by jcubic** [comment] 2017-08-09 16:59
One think to consider, If route tag would be implemented, it would be nice if you could access route variable from inside route like this:

```jsx
      <Route path={"/user/{{name}}"} route={state.route}>
        <UserPage user={state.route.data.name}/>
      </Route>
```
so you can display different user user page.

I've update by demo using oncreate event, that was mention in other issue, https://codepen.io/jcubic/pen/mwvMBV?editors=0010 the only think that is not possible with that demo is initial state if app create and there is already a hash (it's added at the begining) the route is not updated because oncreate is executed after render of the children.

The only thing that is required is to make this work is to update DOM when action is called in oncreate.

**Comment by jbucaran** [comment] 2017-08-16 16:27
I think a new router could easily be made to be used like this:

```jsx
<Router>
  <Route path="/" route={MyView} />
</Router>
```

**Comment by jbucaran** [comment] 2017-08-16 16:31
I am going to close here and ask you to take the discussion to the router repo.

- https://github.com/hyperapp/router/issues/11

Thank you @jcubic @zaceno @lukejacksonn @SkaterDad

**Closed by jbucaran** 2017-08-16 16:31 UTC
Labels: DISCUSSION
