### ISSUE TITLE
IE 9: cannot set the SVG requiredFeatures attribute to an empty string or remove the requiredFeatures attribute

### ISSUE THREAD

**Issue by infinnie** [hyperapp/hyperapp#680] opened 2018-04-22 10:16 UTC
Changing
```svg
<g requiredFeatures="some"/>
```
to
```svg
<g/>
```
Would not work in Hyperapp. We should fall back to an existing feature that is supported by all SVG-compatible browsers to cope with the problem.

**Comment by jorgebucaran** [comment] 2018-04-22 10:26
@infinnie Could you try harder to explain _what_ the problem is?

What about IE10 or IE11?

**Comment by infinnie** [comment] 2018-04-22 10:49
Yes. The problem is demonstrated in this piece of JavaScript code:

```js
var svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
svg.setAttribute("requiredFeatures", "NotExistingFeature");
svg.getAttribute("requiredFeatures"); // "NotExistingFeature"
svg.setAttribute("requiredFeatures", "");
svg.getAttribute("requiredFeatures"); // "NotExistingFeature" in IE 9
svg.setAttribute("requiredFeatures", " "); // A space
svg.getAttribute("requiredFeatures"); // ""

// What works for class should work here, but not in IE 9
svg.setAttribute("class", "NotExistingFeature");
svg.getAttribute("class"); // "NotExistingFeature"
svg.setAttribute("class", "");
svg.getAttribute("class"); // ""
```
I haven’t tested IE 10/11 yet but I will, ASAP.

**Comment by infinnie** [comment] 2018-04-22 14:02
I wasn’t able to test them back then, but I’ve just tested the code on IE11. Although `removeAttribute()` is supported for `requiredFeatures`, `setAttribute("requiredFeatures", "")` would not work.

**Comment by infinnie** [comment] 2018-04-22 14:13
But all in all, an empty string for `requiredFeatures` would make an SVG element fail to get rendered.

**Comment by infinnie** [comment] 2018-04-22 14:30
So in all, though it affects IE 11, it doesn’t break our app logic. IE 9 needs further testing, however.

**Comment by jorgebucaran** [comment] 2018-04-23 03:01
@infinnie What about IE10?

**Comment by jorgebucaran** [comment] 2018-04-23 03:26
@infinnie Hmm, what about using `oncreate` or `onupdate` on an element and use it to set or remove the requiredFeatures attributes? 

I think it goes without saying that we can't add a special condition to the code that updates attributes just for IE9's `requiredFeatures` lack of suppor.

**Comment by jorgebucaran** [comment] 2018-06-23 15:43
Going to close here as wontfix.

**Closed by jorgebucaran** 2018-06-23 15:43 UTC
Labels: NEEDS FEEDBACK
